// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 input vd65768,
 input vfb415d,
 output v266c55,
 output v1cd7a1,
 output vd22322,
 output v5e2ae9,
 output v83bb42
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign v1cd7a1 = w0;
 assign vd22322 = w1;
 assign v5e2ae9 = w2;
 assign v83bb42 = w3;
 assign w4 = vd65768;
 assign v266c55 = w5;
 assign w6 = vfb415d;
 vfebcfe v2c0e14 (
  .v9fb85f(w5)
 );
 main_vec19c0 vec19c0 (
  .ain1(w0),
  .ain2(w1),
  .bin1(w2),
  .bin2(w3),
  .clk(w4),
  .en(w6)
 );
endmodule

//---- Top entity
module vfebcfe (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vfebcfe_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 1
//---------------------------------------------------

module vfebcfe_vb2eccd (
 output q
);
 //-- Constant bit-1
 assign q = 1'b1;
 
 
endmodule

module main_vec19c0 (
 input clk,
 input en,
 output ain1,
 output ain2,
 output bin1,
 output bin2
);
 ///////////////////////////////////////////////////////////////////////////////
 // Stepper Motor Controller for Colorlight 5A-75B
 // No inputs required - runs automatically on power-up
 // Outputs: ain1, ain2, bin1, bin2
 // Clock: 25 MHz (5A-75B typical)
 ///////////////////////////////////////////////////////////////////////////////
 
 
     // Speed control - adjust this value to change motor speed
     // Formula: CLKS_PER_STEP = CLK_FREQ / (RPM * STEPS_PER_REV / 60)
     // For 25 MHz clock, 60 RPM, 200 steps/rev: 25,000,000 / 200 = 125,000
     localparam CLKS_PER_STEP = 125_000;  // ~60 RPM
     reg a1 , a2 , b1 ,b2 ;
     // Timing counter
     reg [23:0] speed_counter;
     
     // Step sequence state (half-step mode for smooth operation)
     reg [2:0] state;
     
     // State definitions
     localparam S0 = 3'b000;   // A+, B+
     localparam S1 = 3'b001;   // A+, off
     localparam S2 = 3'b010;   // A-, B+
     localparam S3 = 3'b011;   // off, B+
     localparam S4 = 3'b100;   // A-, B-
     localparam S5 = 3'b101;   // A-, off
     localparam S6 = 3'b110;   // A+, B-
     localparam S7 = 3'b111;   // off, B-
     
     // Clock divider and state machine
     always @(posedge clk) begin
         if (speed_counter >= CLKS_PER_STEP - 1) begin
             speed_counter <= 0;
             // Advance to next state
             if (state == S7)
                 state <= S0;
             else
                 state <= state + 1;
         end else begin
             speed_counter <= speed_counter + 1;
         end
     end
     
     // Output decoder - generates the four control signals
     always @(*) begin
         if (en == 0) begin
         case (state)
             S0: begin  // A+, B+
                 a1 = 1'b1; a2 = 1'b0;
                 b1 = 1'b1; b2 = 1'b0;
             end
             S1: begin  // A+, off
                 a1 = 1'b1; a2 = 1'b0;
                 b1 = 1'b0;b2 = 1'b0;
             end
             S2: begin  // A-, B+
                 a1 = 1'b0;a2 = 1'b1;
                 b1 = 1'b1;b2 = 1'b0;
             end
             S3: begin  // off, B+
                 a1 = 1'b0;a2 = 1'b0;
                 b1 = 1'b1;b2 = 1'b0;
             end
             S4: begin  // A-, B-
                 a1 = 1'b0; a2 = 1'b1;
                 b1 = 1'b0; b2 = 1'b1;
             end
             S5: begin  // A-, off
                 a1 = 1'b0; a2 = 1'b1;
                 b1 = 1'b0; b2 = 1'b0;
             end
             S6: begin  // A+, B-
                 a1 = 1'b1; a2 = 1'b0;
                 b1 = 1'b0; b2 = 1'b1;
             end
             S7: begin  // off, B-
                 a1 = 1'b0; a2 = 1'b0;
                 b1 = 1'b0; b2 = 1'b1;
             end
             default: begin
                 a1 = 1'b0; a2 = 1'b0;
                 b1 = 1'b0; b2 = 1'b0;
             end
         endcase
         end
     end
     assign ain1 = a1;
     assign ain2 = a2;
     assign bin1 = b1;
     assign bin2 = b2;
 
endmodule
